language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

# 
# Prepare autotools and install dependencies before installation
#
before_install:
  # 
  # Use GNU autotools to generate ./configure automatically on linux
  # 
  # - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  #    mkdir m4 ;
  #    autoreconf -i ;
  #  fi
  # 
  # Install GSL, Boost, HDF5, readline, ncurses
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install libgsl0-dev && sudo apt-get install libboost-all-dev libhdf5-dev libreadline-dev libncurses-dev;
    fi

#
# Installation script
#
# On Mac, using "install:" doesn't work here b/c it additionally
# tries to run ./configure after doing the homebrew installation,
# so we use "script:" here instead
#
script:
  # 
  # Perform the installation on linux. Since there is no documentation,
  # 'make blank-doc' is used to create dummy documentation so that
  # 'make install' does not fail. 
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir o2scl && cd o2scl && git clone https://github.com/awsteiner/o2scl && mkdir m4 && autoreconf -i && ./configure && make blank-doc && make install && cd .. && make rel && make nr && nr check && rel check ;
    fi
  # 
  # Use homebrew to install the HEAD version on OSX. At the end,
  # 'acol --version' is used to double check that the install worked.
  # We need to use '-v' for brew install so that the build doesn't timeout.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew install homebrew/science/hdf5 && brew tap awsteiner/science && which autoconf && brew install o2scl --HEAD -v && make rel && make nr && nr check && rel check ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
