language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

before_install:
  # 
  # On Linux, set LD_LIBRARY_PATH so the executable can find the
  # o2scl libraries
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib ;
    fi
  # 
  # Install GSL, Boost, HDF5, readline, ncurses
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install libgsl0-dev && sudo apt-get install libboost-all-dev libhdf5-dev libreadline-dev libncurses-dev ;
    fi

#
# Installation script
#
script:
  # 
  # Perform the installation on linux. 
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      git clone https://github.com/awsteiner/o2scl && cd o2scl && mkdir m4 && autoreconf -i && ./configure && make blank-doc && sudo make install && cd .. && ls /usr/local/lib && make nr && make rel && make check ;
    fi
  #
  # Use homebrew to install the HEAD version of o2scl on OSX. We need
  # to use '-v' for brew install so that the build doesn't timeout.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew install homebrew/science/hdf5 && brew tap awsteiner/science && which autoconf && brew install o2scl --HEAD -v && make nr && make rel && make check;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
