language: cpp

os:
  - linux
# For now, ignore OSX compilation since its too time consuming
#  - osx

sudo: required

# Set up the environment variables for the snap installation of
# o2scl on linux. We need four library directories on both
# LD_LIBRARY_PATH and LDFLAGS
#
# /snap/o2scl/current/usr/lib/x86_64-linux-gnu
# /snap/o2scl/current/lib/x86_64-linux-gnu
# /snap/o2scl/current/lib
# /snap/o2scl/current/usr/lib/x86_64-linux-gnu/hdf5/serial
#
# For includes, we need the three directories
# 
# /snap/o2scl/current/include
# /snap/o2scl/current/usr/include
# /snap/o2scl/current/usr/include/hdf5/serial
# 

env:
  - LD_LIBRARY_PATH="/snap/o2scl/current/usr/lib/x86_64-linux-gnu:/snap/o2scl/current/lib/x86_64-linux-gnu:/snap/o2scl/current/lib:/snap/o2scl/current/usr/lib/x86_64-linux-gnu/hdf5/serial" PATH="/usr/local/bin:/usr/bin:/bin:/snap/o2scl/current/bin" CXX="g++" LDFLAGS="-L/snap/o2scl/current/usr/lib/x86_64-linux-gnu -L/snap/o2scl/current/lib/x86_64-linux-gnu -L/snap/o2scl/current/lib -L/snap/o2scl/current/usr/lib/x86_64-linux-gnu/hdf5/serial" CXXFLAGS="-I/snap/o2scl/current/include -I/snap/o2scl/current/usr/include -I/snap/o2scl/current/usr/include/hdf5/serial"

# Install o2scl

addons:
  snaps:
    - name: o2scl
      confinement: devmode
      channel: latest/edge

# We use 'acol --version' to verify the o2scl installation and
# then install o2graph and verify that installation with o2graph -help

#
# Compile
#

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
       acol --version && make nr && make rel ;
    fi

#
# Test
#
script:
  # 
  # Perform the installation on linux. 
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      make travis-check ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
